// AUTO-GENERATED by gen_wasm_bindings.py — DO NOT EDIT.
// Regenerate: python3 core/wasm/tools/gen_wasm_bindings.py \
//   --manifest core/wasm/bindings.yml \
//   --output   core/wasm/src/RootWasmBindings_generated.cxx

#ifdef __EMSCRIPTEN__
#include <emscripten/bind.h>
using namespace emscripten;

#include "TH1.h"
#include "TH2.h"
#include "TProfile.h"
#include "TGraphErrors.h"
#include "TMultiGraph.h"
#include "TVector3.h"
#include "TLorentzVector.h"

// ── TH1D ────────────────────────────────────────────────────────────────
EMSCRIPTEN_BINDINGS(TH1D_gen_bindings)
{
  class_<TH1D, base<TH1>>("TH1D")
    .constructor<>()
    .function("Reset", &TH1D::Reset)
    .function("SetBinsLength", &TH1D::SetBinsLength)
    .function("GetBinContent1", optional_override([](const TH1D &h, int bin){ return h.GetBinContent(bin); }))
    .function("GetBinCenter",   optional_override([](const TH1D &h, int bin){ return h.GetBinCenter(bin); }))
    .function("GetNbinsX",      optional_override([](const TH1D &h){ return h.GetNbinsX(); }))
    ;
}

// ── TH1I ────────────────────────────────────────────────────────────────
EMSCRIPTEN_BINDINGS(TH1I_gen_bindings)
{
  class_<TH1I, base<TH1>>("TH1I")
    .constructor<>()
    .function("Reset", &TH1I::Reset)
    .function("SetBinsLength", &TH1I::SetBinsLength)
    .function("GetBinContent1", optional_override([](const TH1I &h, int bin){ return (double)h.GetBinContent(bin); }))
    .function("GetNbinsX",      optional_override([](const TH1I &h){ return h.GetNbinsX(); }))
    ;
}

// ── TH2D ────────────────────────────────────────────────────────────────
EMSCRIPTEN_BINDINGS(TH2D_gen_bindings)
{
  class_<TH2D, base<TH2>>("TH2D")
    .constructor<>()
    .function("Reset", &TH2D::Reset)
    .function("SetBinsLength", &TH2D::SetBinsLength)
    .function("GetBinContent2", optional_override([](const TH2D &h, int bx, int by){ return h.GetBinContent(bx,by); }))
    .function("GetNbinsX",      optional_override([](const TH2D &h){ return h.GetNbinsX(); }))
    .function("GetNbinsY",      optional_override([](const TH2D &h){ return h.GetNbinsY(); }))
    ;
}

// ── TProfile ────────────────────────────────────────────────────────────
EMSCRIPTEN_BINDINGS(TProfile_gen_bindings)
{
  class_<TProfile, base<TH1D>>("TProfile")
    .constructor<>()
    .function("Approximate", &TProfile::Approximate)
    .function("BufferEmpty", &TProfile::BufferEmpty)
    .function("BuildOptions", &TProfile::BuildOptions)
    .function("FillN", &TProfile::FillN)
    .function("GetBinEffectiveEntries", &TProfile::GetBinEffectiveEntries)
    .function("GetErrorOption", &TProfile::GetErrorOption)
    .function("GetStats", &TProfile::GetStats)
    .function("GetYmin", &TProfile::GetYmin)
    .function("GetYmax", &TProfile::GetYmax)
    .function("LabelsDeflate", &TProfile::LabelsDeflate)
    .function("LabelsInflate", &TProfile::LabelsInflate)
    .function("LabelsOption", &TProfile::LabelsOption)
    .function("PutStats", &TProfile::PutStats)
    .function("Reset", &TProfile::Reset)
    .function("Scale", &TProfile::Scale)
    .function("SetBinEntries", &TProfile::SetBinEntries)
    .function("SetBinsLength", &TProfile::SetBinsLength)
    .function("SetBuffer", &TProfile::SetBuffer)
    .function("SetErrorOption", &TProfile::SetErrorOption)
    .function("Sumw2", &TProfile::Sumw2)
    .function("GetBinEntries", optional_override([](const TProfile &h, int bin){ return h.GetBinEntries(bin); }))
    ;
}

// ── TGraphErrors ────────────────────────────────────────────────────────
EMSCRIPTEN_BINDINGS(TGraphErrors_gen_bindings)
{
  class_<TGraphErrors, base<TGraph>>("TGraphErrors")
    .constructor<>()
    .constructor<int>()
    .function("AddPointError", &TGraphErrors::AddPointError)
    .function("CalculateScanfFields", &TGraphErrors::CalculateScanfFields)
    .function("ComputeRange", &TGraphErrors::ComputeRange)
    .function("GetErrorXhigh", &TGraphErrors::GetErrorXhigh)
    .function("GetErrorXlow", &TGraphErrors::GetErrorXlow)
    .function("GetErrorYhigh", &TGraphErrors::GetErrorYhigh)
    .function("GetErrorYlow", &TGraphErrors::GetErrorYlow)
    .function("GetEX", &TGraphErrors::GetEX)
    .function("GetEY", &TGraphErrors::GetEY)
    .function("Print", &TGraphErrors::Print)
    .function("Scale", &TGraphErrors::Scale)
    .function("SetPointError",  optional_override([](TGraphErrors &g, int i, double ex, double ey){ g.SetPointError(i, ex, ey); }))
    .function("GetErrorX",      optional_override([](const TGraphErrors &g, int i){ return g.GetErrorX(i); }))
    .function("GetErrorY",      optional_override([](const TGraphErrors &g, int i){ return g.GetErrorY(i); }))
    ;
}

// ── TMultiGraph ─────────────────────────────────────────────────────────
EMSCRIPTEN_BINDINGS(TMultiGraph_gen_bindings)
{
  class_<TMultiGraph, base<TNamed>>("TMultiGraph")
    .constructor<>()
    .function("DistancetoPrimitive", &TMultiGraph::DistancetoPrimitive)
    .function("FitPanel", &TMultiGraph::FitPanel)
    .function("LeastSquareLinearFit", &TMultiGraph::LeastSquareLinearFit)
    .function("LeastSquareFit", &TMultiGraph::LeastSquareFit)
    .function("InitPolynom", &TMultiGraph::InitPolynom)
    .function("InitExpo", &TMultiGraph::InitExpo)
    .function("InitGaus", &TMultiGraph::InitGaus)
    .function("IsInside", &TMultiGraph::IsInside)
    .function("Paint", &TMultiGraph::Paint)
    .function("PaintPads", &TMultiGraph::PaintPads)
    .function("PaintPolyLine3D", &TMultiGraph::PaintPolyLine3D)
    .function("PaintReverse", &TMultiGraph::PaintReverse)
    .function("Print", &TMultiGraph::Print)
    .function("SetMaximum", &TMultiGraph::SetMaximum)
    .function("SetMinimum", &TMultiGraph::SetMinimum)
    .function("AddGraph", optional_override([](TMultiGraph &mg, TGraph *g){ mg.Add(g, "lp"); }), allow_raw_pointers())
    ;
}

// ── TVector3 ────────────────────────────────────────────────────────────
EMSCRIPTEN_BINDINGS(TVector3_gen_bindings)
{
  class_<TVector3, base<TObject>>("TVector3")
    .constructor<>()
    .constructor<double, double, double>()
    .function("x", &TVector3::x)
    .function("y", &TVector3::y)
    .function("z", &TVector3::z)
    .function("Px", &TVector3::Px)
    .function("Py", &TVector3::Py)
    .function("Pz", &TVector3::Pz)
    .function("SetX", &TVector3::SetX)
    .function("SetY", &TVector3::SetY)
    .function("SetZ", &TVector3::SetZ)
    .function("SetXYZ", &TVector3::SetXYZ)
    .function("SetPtEtaPhi", &TVector3::SetPtEtaPhi)
    .function("SetPtThetaPhi", &TVector3::SetPtThetaPhi)
    .function("CosTheta", &TVector3::CosTheta)
    .function("Mag2", &TVector3::Mag2)
    .function("SetPhi", &TVector3::SetPhi)
    .function("SetTheta", &TVector3::SetTheta)
    .function("SetMag", &TVector3::SetMag)
    .function("SetPerp", &TVector3::SetPerp)
    .function("SetMagThetaPhi", &TVector3::SetMagThetaPhi)
    .function("PseudoRapidity", &TVector3::PseudoRapidity)
    .function("Eta", &TVector3::Eta)
    .function("RotateX", &TVector3::RotateX)
    .function("RotateY", &TVector3::RotateY)
    .function("RotateZ", &TVector3::RotateZ)
    .function("Print", &TVector3::Print)
    .function("X", &TVector3::X)
    .function("Y", &TVector3::Y)
    .function("Z", &TVector3::Z)
    .function("Mag",   &TVector3::Mag)
    .function("Phi",   &TVector3::Phi)
    .function("Theta", &TVector3::Theta)
    .function("Dot",   &TVector3::Dot)
    ;
}

// ── TLorentzVector ──────────────────────────────────────────────────────
EMSCRIPTEN_BINDINGS(TLorentzVector_gen_bindings)
{
  class_<TLorentzVector, base<TObject>>("TLorentzVector")
    .constructor<>()
    .constructor<double, double, double, double>()
    .function("SetX", &TLorentzVector::SetX)
    .function("SetY", &TLorentzVector::SetY)
    .function("SetZ", &TLorentzVector::SetZ)
    .function("SetT", &TLorentzVector::SetT)
    .function("P", &TLorentzVector::P)
    .function("Energy", &TLorentzVector::Energy)
    .function("SetPx", &TLorentzVector::SetPx)
    .function("SetPy", &TLorentzVector::SetPy)
    .function("SetPz", &TLorentzVector::SetPz)
    .function("SetE", &TLorentzVector::SetE)
    .function("Theta", &TLorentzVector::Theta)
    .function("CosTheta", &TLorentzVector::CosTheta)
    .function("Rho", &TLorentzVector::Rho)
    .function("SetTheta", &TLorentzVector::SetTheta)
    .function("SetPhi", &TLorentzVector::SetPhi)
    .function("SetRho", &TLorentzVector::SetRho)
    .function("SetPxPyPzE", &TLorentzVector::SetPxPyPzE)
    .function("SetXYZT", &TLorentzVector::SetXYZT)
    .function("SetXYZM", &TLorentzVector::SetXYZM)
    .function("SetPtEtaPhiM", &TLorentzVector::SetPtEtaPhiM)
    .function("SetPtEtaPhiE", &TLorentzVector::SetPtEtaPhiE)
    .function("SetPerp", &TLorentzVector::SetPerp)
    .function("Mag2", &TLorentzVector::Mag2)
    .function("Mag", &TLorentzVector::Mag)
    .function("Mt2", &TLorentzVector::Mt2)
    .function("Mt", &TLorentzVector::Mt)
    .function("Beta", &TLorentzVector::Beta)
    .function("Gamma", &TLorentzVector::Gamma)
    .function("Plus", &TLorentzVector::Plus)
    .function("Minus", &TLorentzVector::Minus)
    .function("Rapidity", &TLorentzVector::Rapidity)
    .function("PseudoRapidity", &TLorentzVector::PseudoRapidity)
    .function("RotateX", &TLorentzVector::RotateX)
    .function("RotateY", &TLorentzVector::RotateY)
    .function("RotateZ", &TLorentzVector::RotateZ)
    .function("X",   &TLorentzVector::X)
    .function("Y",   &TLorentzVector::Y)
    .function("Z",   &TLorentzVector::Z)
    .function("T",   &TLorentzVector::T)
    .function("E",   &TLorentzVector::E)
    .function("Px",  &TLorentzVector::Px)
    .function("Py",  &TLorentzVector::Py)
    .function("Pz",  &TLorentzVector::Pz)
    .function("M",   &TLorentzVector::M)
    .function("M2",  &TLorentzVector::M2)
    .function("Pt",  &TLorentzVector::Pt)
    .function("Eta", &TLorentzVector::Eta)
    .function("Phi", &TLorentzVector::Phi)
    ;
}

#endif  // __EMSCRIPTEN__
